"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var rectangle_1 = require("./rectangle");
var circle_1 = require("./circle");
var circleObj = new circle_1.Circle(2);
circleObj.Myarea();
circleObj.display();
var rectObj = new rectangle_1.Rectangle(2, 3);
rectObj.Myarea();
rectObj.dispaly();
